#!/bin/bash
#
# Zero Email - Standalone Installation Script
#
# One-line install:
#   curl -fsSL https://raw.githubusercontent.com/Mail-0/Zero/staging/scripts/install-standalone.sh | bash
#
# This script installs Zero Email on a Raspberry Pi or any Linux system with Docker.
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REPO_URL="https://github.com/Mail-0/Zero.git"
BRANCH="staging"
INSTALL_DIR="${ZERO_INSTALL_DIR:-$HOME/zero-email}"

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║              Zero Email - Standalone Installer                ║"
echo "║                                                               ║"
echo "║   Self-hosted email client with MinIO, PostgreSQL & Redis    ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check system requirements
check_requirements() {
    echo -e "${BLUE}[1/5]${NC} Checking system requirements..."

    # Check for Docker
    if ! command -v docker &> /dev/null; then
        echo -e "${YELLOW}Docker not found. Installing Docker...${NC}"
        curl -fsSL https://get.docker.com | sh
        sudo usermod -aG docker $USER
        echo -e "${YELLOW}Docker installed. You may need to log out and back in for group changes.${NC}"
    else
        echo -e "${GREEN}✓ Docker is installed${NC}"
    fi

    # Check for Docker Compose
    if ! docker compose version &> /dev/null; then
        echo -e "${YELLOW}Docker Compose not found. Installing...${NC}"
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
    else
        echo -e "${GREEN}✓ Docker Compose is installed${NC}"
    fi

    # Check available memory
    TOTAL_MEM=$(free -m | awk '/^Mem:/{print $2}')
    if [ "$TOTAL_MEM" -lt 2000 ]; then
        echo -e "${RED}Warning: Less than 2GB RAM detected ($TOTAL_MEM MB).${NC}"
        echo -e "${YELLOW}Zero Email requires at least 2GB RAM, 4GB recommended.${NC}"
        read -p "Continue anyway? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    else
        echo -e "${GREEN}✓ Sufficient memory: ${TOTAL_MEM}MB${NC}"
    fi

    # Check available disk space
    AVAIL_DISK=$(df -m "$HOME" | awk 'NR==2 {print $4}')
    if [ "$AVAIL_DISK" -lt 10000 ]; then
        echo -e "${YELLOW}Warning: Less than 10GB disk space available.${NC}"
    else
        echo -e "${GREEN}✓ Sufficient disk space: ${AVAIL_DISK}MB${NC}"
    fi
}

# Clone or update repository
setup_repository() {
    echo -e "${BLUE}[2/5]${NC} Setting up repository..."

    if [ -d "$INSTALL_DIR" ]; then
        echo -e "${YELLOW}Directory exists. Updating...${NC}"
        cd "$INSTALL_DIR"
        git fetch origin
        git checkout "$BRANCH"
        git pull origin "$BRANCH"
    else
        echo "Cloning Zero Email repository..."
        git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
        cd "$INSTALL_DIR"
    fi

    echo -e "${GREEN}✓ Repository ready at $INSTALL_DIR${NC}"
}

# Configure environment
configure_environment() {
    echo -e "${BLUE}[3/5]${NC} Configuring environment..."

    cd "$INSTALL_DIR"

    if [ ! -f .env ]; then
        if [ -f .env.example ]; then
            cp .env.example .env
            echo -e "${GREEN}✓ Created .env from template${NC}"
        else
            # Create minimal .env
            cat > .env << 'EOF'
# Zero Email Standalone Configuration
# Generated by install-standalone.sh

# Database
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=zerodotemail

# MinIO (S3-compatible storage)
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
S3_BUCKET=threads

# Authentication (CHANGE IN PRODUCTION!)
BETTER_AUTH_SECRET=change-me-in-production-use-openssl-rand-base64-32
JWT_SECRET=change-me-in-production-use-openssl-rand-base64-32

# App URLs (update with your domain/IP)
APP_URL=http://localhost:3000
BACKEND_URL=http://localhost:3000/api
BASE_URL=http://localhost:3000
COOKIE_DOMAIN=localhost
BETTER_AUTH_TRUSTED_ORIGINS=http://localhost:3000

# Google OAuth (required for Gmail access)
# Get credentials at: https://console.cloud.google.com/
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=http://localhost:3000/api/auth/callback/google

# Optional: AI features
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
EOF
            echo -e "${GREEN}✓ Created default .env file${NC}"
        fi

        echo -e "${YELLOW}"
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║  IMPORTANT: Configure Google OAuth credentials in .env        ║"
        echo "║                                                               ║"
        echo "║  1. Go to https://console.cloud.google.com/                   ║"
        echo "║  2. Create a project and enable Gmail API                     ║"
        echo "║  3. Create OAuth 2.0 credentials                              ║"
        echo "║  4. Set redirect URI to your-ip:3000/api/auth/callback/google ║"
        echo "║  5. Add GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET to .env     ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo -e "${NC}"
    else
        echo -e "${GREEN}✓ Using existing .env configuration${NC}"
    fi
}

# Start services
start_services() {
    echo -e "${BLUE}[4/5]${NC} Starting services..."

    cd "$INSTALL_DIR"

    # Pull latest images
    echo "Pulling Docker images (this may take a while on first run)..."
    docker compose -f docker-compose.standalone.yaml pull 2>/dev/null || true

    # Start services
    echo "Starting Zero Email services..."
    docker compose -f docker-compose.standalone.yaml up -d

    echo -e "${GREEN}✓ Services started${NC}"
}

# Wait for services and show status
show_status() {
    echo -e "${BLUE}[5/5]${NC} Waiting for services to be ready..."

    cd "$INSTALL_DIR"

    # Wait for health check
    echo "Waiting for server to be healthy..."
    RETRIES=30
    while [ $RETRIES -gt 0 ]; do
        if curl -s http://localhost:3000/health > /dev/null 2>&1; then
            break
        fi
        RETRIES=$((RETRIES-1))
        echo -n "."
        sleep 2
    done
    echo

    if [ $RETRIES -eq 0 ]; then
        echo -e "${YELLOW}Server is still starting. Check logs with:${NC}"
        echo "  docker compose -f docker-compose.standalone.yaml logs -f server"
    else
        echo -e "${GREEN}✓ Server is healthy${NC}"
    fi

    # Get local IP
    LOCAL_IP=$(hostname -I | awk '{print $1}')

    echo -e "${GREEN}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║                                                               ║"
    echo "║              Zero Email is ready!                             ║"
    echo "║                                                               ║"
    echo "╠═══════════════════════════════════════════════════════════════╣"
    echo "║                                                               ║"
    echo "║  Web App:        http://$LOCAL_IP:3000                   ║"
    echo "║  MinIO Console:  http://$LOCAL_IP:9001                   ║"
    echo "║  Job Queue UI:   http://$LOCAL_IP:3000/admin/queues      ║"
    echo "║                                                               ║"
    echo "╠═══════════════════════════════════════════════════════════════╣"
    echo "║  MinIO Credentials: minioadmin / minioadmin                   ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"

    echo -e "${BLUE}Useful commands:${NC}"
    echo "  View logs:     docker compose -f docker-compose.standalone.yaml logs -f"
    echo "  Stop:          docker compose -f docker-compose.standalone.yaml down"
    echo "  Restart:       docker compose -f docker-compose.standalone.yaml restart"
    echo "  Update:        git pull && docker compose -f docker-compose.standalone.yaml up -d --build"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Configure Google OAuth in $INSTALL_DIR/.env"
    echo "  2. Restart: docker compose -f docker-compose.standalone.yaml restart server"
    echo "  3. Access http://$LOCAL_IP:3000 and sign in with Google"
    echo ""
}

# Main installation flow
main() {
    check_requirements
    setup_repository
    configure_environment
    start_services
    show_status
}

# Run main function
main
